language: rust
sudo: false
cache: cargo

matrix:
  include:
    - os: linux
    - os: osx
    - rust: stable
      env: FEATURES=''
    - rust: beta
      env: FEATURES=''
    - rust: nightly
      env: FEATURES='nightly'

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

script:
  - cargo build --features "$FEATURES" --verbose
  - cargo test --features "$FEATURES" --verbose
  - rustdoc --test README.md -L target
  - cargo doc --no-deps
  # Only run benchmarks against the nightly build until benchmarking is
  # available in stable.
  - test "$FEATURES" != "" && cargo bench --features "$FEATURES" -- --test --nocapture || echo "Skipping benchmarks"

notifications:
  email:
    on_success: never

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
