language: rust
matrix:
  include:
    - rust: stable
      env: FEATURES=''
    - rust: beta
      env: FEATURES=''
    - rust: nightly
      env: FEATURES=nightly
  allow_failures:
    - rust: nightly
sudo: false
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - cargo build --features "$FEATURES"
  - cargo test --features "$FEATURES"
  - rustdoc --test README.md -L target
  - test "$TRAVIS_RUST_VERSION" != "1.15.0" && cargo doc --no-deps || echo "skipping cargo doc"
  - cargo bench --features "$FEATURES" -- --test --nocapture
notifications:
  email:
    on_success: never
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
