
    Hello = "world"
    value = 5
array = [true, true, false] # Array
bool = true
a_date = 1979-05-27T00:32:00.999999-07:00
single = "Fluctat nec mergitur"
multi = """/
Lorem ipsum /
           dolor sit /
           amet./
           """# Comment from hell
singleL = 'Vulnerant omnes, ultima necat'
multiL = '''
    Sic
    Semper
    Tyrannis
    '''

neg = -59

[table]
    hello = "world"
    this = "works"
    does = "this?"


    long = "shot"

[second.table]
true = false
list = ["Er", "mah", "Gahd!"]