
    Hello = "world"
    value = 5
array = [true, true, false] # Array
bool = true
# Full line comment
a_date = 1979-05-27T00:32:00.999999-07:00
single = "Fluctat nec mergitur"
multi = """/
           Lorem ipsum /
           dolor sit /
           amet./
           """# Comment from hell
singleL = 'Vulnerant omnes, ultima necat'
multiL = '''
    Sic
    Semper
    Tyrannis
    '''

neg = -59
inline = {a = true, b = true, c = false}

[table]
    broken_array = [1, 2, 3, 4]
        hello = "world"
    this = "works"
    does = "this?"
    # lone comment here?
    it_does = true#WOW

    long = "shot"

    [table.nested]
    value = 1
    other_value = 2

    [second.table]#Table comment
true = false
list = ["Er", "mah", "Gahd!"]
# Finish Him!
inline = {a = true, b = true, c = false}

[[parsethis]]
a = 1
b = 2
[[parsethis.sub]]
flag = true
[[parsethis.sub]]
flag = false

[[parsethis]]
b = 1
c = 3

[[parsethis]]
a = 4
inline = {a = true, b = true, c = false}

[[other_AoT]]
flag = true

[[other_AoT]]
flag = false
[[other_AoT]]
flag = false

[tableattheend]
inline = {a = true, b = true, c = false}